apiVersion: v1
kind: ConfigMap
metadata:
  name: netca-configmap
  namespace: ${name-space}
  labels:
    app: netca
    workstream: dad
    version: "${app-version}"
    tier: backend
    postgre: "true"
    eventhub: "true"
    redis: "true"
    usermanagementservice: "true"
    equipmentmonitoringservice: "true"
data:
  App__Title: "NetCa"
  App__Description: "DAD .NET Clean Architecture Web Api Solution Template"
  App__Version: "${app-version}"
  App__UrlWeb: "${app-urlweb}"
  IsEnableAuth: "true"
  IsEnableDetailError: "false"
  CorsOrigin: "https://*.unitedtractors.com"
  Kestrel__KeepAliveTimeoutInM: "2"
  Kestrel__MinRequestBodyDataRate__bytesPerSecond: "100"
  Kestrel__MinRequestBodyDataRate__gracePeriod: "10"
  Kestrel__MinResponseDataRate__bytesPerSecond: "100"
  Kestrel__MinResponseDataRate__gracePeriod: "10"
  DatabaseSettings__CommandTimeout: "600"
  DatabaseSettings__MaxRetryCount: "100"
  DatabaseSettings__MaxRetryDelay: "5"
  DatabaseSettings__EnableAuditChangelog: "true"
  Messaging__AzureEventHub__0__BlobContainerName: "eventhub"
  Messaging__Configuration__SaveToDb: "true"
  Messaging__Configuration__MaxData: "300"
  Messaging__Configuration__MessageToProcess: "25"
  Messaging__Configuration__ProcessDelay: "10"
  RedisServer__InstanceName: "netca"
  RedisServer__DefaultExpiryInDays: "30"
  RedisServer__RequestExpiryInMinutes: "30"
  RedisServer__MessageExpiryInDays: "180"
  AuthorizationServer__Gateway: "${authorizationserver-gateway}"
  AuthorizationServer__Address: "${authorizationserver-address}"
  AuthorizationServer__Service: "netca"
  AuthorizationServer__Header: "Ocp-Apim-Subscription-Key"
  BackgroundJob__IsEnable: "true"
  BackgroundJob__DefaultMaxRunTime: "10"
  BackgroundJob__UsePersistentStore: "true"
  BackgroundJob__PersistentStore__UseCluster: "true"
  BackgroundJob__PersistentStore__IgnoreDuplicates: "true"
  BackgroundJob__PersistentStore__OverWriteExistingData: "true"
  BackgroundJob__PersistentStore__MaxConcurrency: "10"
  BackgroundJob__PersistentStore__RetryInterval: "15"
  BackgroundJob__PersistentStore__CheckInInterval: "15000"
  BackgroundJob__PersistentStore__CheckInMisfireThreshold: "15000"
  BackgroundJob__PersistentStore__MisfireThreshold: "15000"
  BackgroundJob__PersistentStore__TablePrefix: "QRTZ_"
  BackgroundJob__Jobs__0__Schedule: "0 0 */6 ? * *"
  BackgroundJob__Jobs__1__Schedule: "0 */1 * * * ?"
  BackgroundJob__Jobs__2__Schedule: "*/30 * * * * ?"
  BackgroundJob__Jobs__3__Schedule: "0 */1 * * * ?"
  BackgroundJob__Jobs__4__Schedule: "*/30 * * * * ?"
  BackgroundJob__Jobs__5__Schedule: "0 0 2 * * ?"
  DataLifetime__Changelog: "180"
  Bot__IsEnable: "true"
  Bot__ServiceName: "DAD - NetCa"
  Bot__ServiceDomain: "${bot-servicedomain}"
  Bot__Address: "${bot-address}"
  Bot__Header: "Ocp-Apim-Subscription-Key"
  Logging__LogLevel__Default: "Information"
  Logging__LogLevel__Microsoft: "Warning"
  Logging__LogLevel__Microsoft.Hosting.Lifetime: "Warning"
  Serilog__MinimumLevel__Default: "Information"
  Serilog__MinimumLevel__Override__Microsoft: "Warning"
  Serilog__MinimumLevel__Override__System.Hosting.Lifetime: "Warning"
