apiVersion: v1
kind: Secret
metadata:
  labels:
    app: netca
    workstream: dad
    version: "${app-version}"
    tier: backend
    postgre: "true"
    eventhub: "true"
    redis: "true"
    usermanagementservice: "true"
    equipmentmonitoringservice: "true"
  name: netca-secrets
  namespace: ${name-space}
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: "$DATABASE_CONNECTION;Database=netca;Ssl Mode=Require;TrustServerCertificate=true;Pooling=true;MinPoolSize=1;MaxPoolSize=50;CommandTimeout=600;Timeout=200;"
  BackgroundJob__PersistentStore__ConnectionString: "$DATABASE_CONNECTION;Database=quartz;Ssl Mode=Require;TrustServerCertificate=true;Pooling=true;MinPoolSize=1;MaxPoolSize=20;CommandTimeout=600;Timeout=200;"
  Messaging__AzureEventHub__0__ConnectionString: "$EVENTHUB_CONNECTION"
  Messaging__AzureEventHub__0__StorageAccount: "$STORAGE_CONNECTION"
  RedisServer__Server: "$REDIS_CONNECTION"
  AuthorizationServer__Secret: "$APIM_SECRET"
  Bot__Secret: "$APIM_SECRET"
  ApplicationInsights__InstrumentationKey: "$INSIGHT_KEY"
